### ISSUE TITLE
评论区报错

### ISSUE THREAD

**Issue by Chzxxuanzheng** [akyuu-rip/akyuu-rip#3]
Error: API rate limit exceeded for app ID bfb1ab63270cdc12ca72. If you reach out to GitHub Support for help, please include the request ID 17CF:0A52:8252C:880ED:66B24D17 and timestamp 2024-08-06 16:19:36 UTC..

**Comment by Chzxxuanzheng** [comment]
建议加一个访问人说太多的提示

**Comment by akyuu-rip** [comment]
github的锅。。懒得弄 又不是看不懂 过一会就好了
